Extension { #name : 'Message' }

{ #category : 'comparing' }
Message >> analogousCodeTo: anObject [

	<PharoGsError>
    self _gsError

]

{ #category : 'accessing' }
Message >> lookupClass [

	<PharoGsError>
    self _gsError

]

{ #category : 'private' }
Message >> lookupClass: aClass [

	<PharoGsError>
    self _gsError

]

{ #category : 'sending' }
Message >> sentTo: receiver [

	<PharoGsError>
    self _gsError

]
