Extension { #name : 'X11Encoding' }

{ #category : 'accessing' }
X11Encoding class >> getEncoding [

	<PharoGsError>
    ^self _gsError

]

{ #category : 'accessing' }
X11Encoding class >> getLocaleEncoding [

	<PharoGsError>
    ^self _gsError

]

{ #category : 'accessing' }
X11Encoding class >> getPathEnc [

	<PharoGsError>
    ^self _gsError

]

{ #category : 'accessing' }
X11Encoding class >> getTextEnc [

	<PharoGsError>
    ^self _gsError

]

{ #category : 'accessing' }
X11Encoding class >> getXWinEnc [

	<PharoGsError>
    ^self _gsError

]

{ #category : 'accessing' }
X11Encoding class >> requestUTF8 [

	<PharoGsError>
    ^self _gsError

]

{ #category : 'accessing' }
X11Encoding class >> requestUTF8: bool [

	<PharoGsError>
    ^self _gsError

]

{ #category : 'accessing' }
X11Encoding class >> setEncoding: encoding [

	<PharoGsError>
    ^self _gsError

]

{ #category : 'accessing' }
X11Encoding class >> setEncodingToLocale [

	<PharoGsError>
    ^self _gsError

]

{ #category : 'accessing' }
X11Encoding class >> setPathEnc: encoding [

	<PharoGsError>
    ^self _gsError

]

{ #category : 'accessing' }
X11Encoding class >> setPathEncToLocale [

	<PharoGsError>
    ^self _gsError

]

{ #category : 'accessing' }
X11Encoding class >> setTextEnc: encoding [

	<PharoGsError>
    ^self _gsError

]

{ #category : 'accessing' }
X11Encoding class >> setTextEncToLocale [

	<PharoGsError>
    ^self _gsError

]

{ #category : 'accessing' }
X11Encoding class >> setXWinEnc: encoding [

	<PharoGsError>
    ^self _gsError

]

{ #category : 'accessing' }
X11Encoding class >> setXWinEncToLocale [

	<PharoGsError>
    ^self _gsError

]
